-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  level int default 1,
  xp int default 0,
  wins int default 0,
  losses int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Active RLS on profiles to secure data
alter table profiles enable row level security;

-- Allow public read access to profiles (leaderboards etc)
create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

-- Allow users to update their own profile
create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create table for character unlocks
create table unlocks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  character_id text not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, character_id)
);

-- RLS for unlocks
alter table unlocks enable row level security;

create policy "Users can see their own unlocks." on unlocks
  for select using (auth.uid() = user_id);

-- Simple Function to handle user creation (can be done via trigger too but this is a manual start)
